// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPreset(arg1, arg2) {
  return window['go']['main']['App']['ApplyPreset'](arg1, arg2);
}

export function ApplyPresetToSpecies(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyPresetToSpecies'](arg1, arg2, arg3);
}

export function BaseCamps(arg1) {
  return window['go']['main']['App']['BaseCamps'](arg1);
}

export function BasePals(arg1) {
  return window['go']['main']['App']['BasePals'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function GiveItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['GiveItem'](arg1, arg2, arg3);
}

export function Inventory(arg1) {
  return window['go']['main']['App']['Inventory'](arg1);
}

export function OpenSave(arg1) {
  return window['go']['main']['App']['OpenSave'](arg1);
}

export function PalSpecies(arg1) {
  return window['go']['main']['App']['PalSpecies'](arg1);
}

export function Pals(arg1) {
  return window['go']['main']['App']['Pals'](arg1);
}

export function PickSaveFile() {
  return window['go']['main']['App']['PickSaveFile']();
}

export function Players() {
  return window['go']['main']['App']['Players']();
}

export function Presets() {
  return window['go']['main']['App']['Presets']();
}

export function SavePreset(arg1, arg2) {
  return window['go']['main']['App']['SavePreset'](arg1, arg2);
}

export function SaveToDisk() {
  return window['go']['main']['App']['SaveToDisk']();
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}

export function SearchPassives(arg1) {
  return window['go']['main']['App']['SearchPassives'](arg1);
}

export function SetItemCount(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetItemCount'](arg1, arg2, arg3);
}

export function SetPalLevel(arg1, arg2) {
  return window['go']['main']['App']['SetPalLevel'](arg1, arg2);
}

export function SetPalPassives(arg1, arg2) {
  return window['go']['main']['App']['SetPalPassives'](arg1, arg2);
}

export function SetPalRank(arg1, arg2) {
  return window['go']['main']['App']['SetPalRank'](arg1, arg2);
}

export function SetPalRankBonus(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPalRankBonus'](arg1, arg2, arg3);
}

export function SetPalTalent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPalTalent'](arg1, arg2, arg3);
}

export function SetPalWorkSuitability(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPalWorkSuitability'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function WorkSuitabilityOptions() {
  return window['go']['main']['App']['WorkSuitabilityOptions']();
}
