// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GiveItem(arg1:string,arg2:string,arg3:number):Promise<number>;

export function Inventory(arg1:string):Promise<Array<main.ItemInfo>>;

export function OpenSave(arg1:string):Promise<main.SaveInfo>;

export function PalSpecies(arg1:string):Promise<Array<main.SpeciesSummary>>;

export function Pals(arg1:string):Promise<Array<main.PalInfo>>;

export function PickSaveFile():Promise<string>;

export function Players():Promise<Array<main.PlayerInfo>>;

export function SaveToDisk():Promise<main.SaveResult>;

export function SearchItems(arg1:string):Promise<Array<main.ItemChoice>>;

export function SetItemCount(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetPalLevel(arg1:string,arg2:number):Promise<void>;

export function SetPalLevelBulk(arg1:string,arg2:string,arg3:number):Promise<number>;

export function SetPalRank(arg1:string,arg2:number):Promise<void>;

export function SetPalTalent(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Status():Promise<main.Status>;
