// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {paldata} from '../models';

export function AddPal(arg1:string,arg2:string,arg3:number,arg4:number,arg5:Record<string, number>,arg6:Array<string>,arg7:boolean,arg8:string):Promise<string>;

export function ApplyPreset(arg1:string,arg2:string):Promise<Array<main.PassiveInfo>>;

export function BaseCamps(arg1:string):Promise<Array<main.CampInfo>>;

export function BasePals(arg1:string):Promise<Array<main.PalInfo>>;

export function BaseStorages(arg1:string):Promise<Array<main.StorageInfo>>;

export function DeletePreset(arg1:string):Promise<void>;

export function GiveContainerItem(arg1:string,arg2:string,arg3:number):Promise<number>;

export function GiveItem(arg1:string,arg2:string,arg3:number):Promise<number>;

export function Inventory(arg1:string):Promise<Array<main.ItemInfo>>;

export function OpenSave(arg1:string):Promise<main.SaveInfo>;

export function PalSpecies(arg1:string):Promise<Array<main.SpeciesSummary>>;

export function PalboxSpace(arg1:string):Promise<number>;

export function Pals(arg1:string):Promise<Array<main.PalInfo>>;

export function PickSaveFile():Promise<string>;

export function PlayerDetail(arg1:string):Promise<main.PlayerDetail>;

export function Players():Promise<Array<main.PlayerInfo>>;

export function Presets():Promise<Array<main.PresetInfo>>;

export function Relics(arg1:string):Promise<Array<main.RelicInfo>>;

export function SavePreset(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveToDisk():Promise<main.SaveResult>;

export function SearchItems(arg1:string):Promise<Array<main.ItemChoice>>;

export function SearchPals(arg1:string):Promise<Array<main.PalChoice>>;

export function SearchPassives(arg1:string):Promise<Array<main.PassiveInfo>>;

export function SearchSkills(arg1:string):Promise<Array<main.SkillInfo>>;

export function SetContainerItemCount(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetItemCount(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetPalAlpha(arg1:string,arg2:boolean):Promise<void>;

export function SetPalFriendship(arg1:string,arg2:number):Promise<void>;

export function SetPalGender(arg1:string,arg2:string):Promise<void>;

export function SetPalLevel(arg1:string,arg2:number):Promise<void>;

export function SetPalPassives(arg1:string,arg2:Array<string>):Promise<void>;

export function SetPalRank(arg1:string,arg2:number):Promise<void>;

export function SetPalRankBonus(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetPalSkills(arg1:string,arg2:Array<string>):Promise<void>;

export function SetPalTalent(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetPalWorkSuitability(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetPlayerLevel(arg1:string,arg2:number):Promise<void>;

export function SetPlayerSlotCount(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetPlayerStat(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SetPlayerUnusedPoints(arg1:string,arg2:number):Promise<void>;

export function SetRelic(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetSlotCount(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Status():Promise<main.Status>;

export function WorkSuitabilityOptions():Promise<Array<paldata.WorkSuitability>>;
